#!/bin/bash

FILE="/usr/share/mxflux/help/mxfl-docs"
lang_check=$(echo $LANG|cut -d_ -f1)
lang_check=${lang_check^^}
echo $lang_check
FILE2=$FILE"_"$lang_check".pdf"

echo $FILE2

if [ -e $FILE2 ]; then
    FILE=$FILE2
else
    FILE=$FILE".pdf"
fi

xdg-open $FILE 
